sudo: required
dist: trusty

language:
  cpp

addons:
  apt:
    #sources:
    #  - george-edison55-precise-backports
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev
      - cmake
      - cmake-data
      - libvtk5-dev
      - libvtk5.8

before_install:
  - sudo apt-get -qq update
  - apt-cache search vtk
  - travis_wait sh ./scripts/petsc.sh 3.6.4
  - export PETSC_DIR=$HOME/petsc
  - export PETSC_ARCH=arch-linux2-c-opt
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  