sudo: required
dist: trusty
#os: linux
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev
      - cmake
      - cmake-data
      - libvtk5-dev
      - libvtk5.8
      - gcc-5

cache: ccache

before_install:
  - export CC=gcc-5
  - export CXX=g++-5
  - sudo apt-get -qq update
  - apt-cache search gcc
  - travis_wait sh ./scripts/petsc.sh 3.6.4
  - export PETSC_DIR=$HOME/petsc
  - export PETSC_ARCH=arch-linux2-c-opt
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
