sudo: required
dist: trusty
#os: linux
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev
      - cmake
      - cmake-data
      - libvtk5-dev
      - libvtk5.8
      - gcc-5
      - g++-5

cache:
  directories:
    - $HOME/cached_dependencies_$TRAVIS_OS_NAME

env:
   global:
    - CACHE_DIRECTORY=$HOME/cached_dependencies_$TRAVIS_OS_NAME
    - PETSC_ARCH=arch-linux2-c-opt
    - PETSC_DIR=$CACHE_DIRECTORY/petsc-3.6.4

before_install:
  - export CC=gcc-5
  - export CXX=g++-5
  - travis_wait sh ./scripts/petsc.sh 3.6.4
install:
  - export PETSC_DIR=$PETSC_DIR
  - export PETSC_ARCH=$PETSC_ARCH
  - mkdir build
  - cd build
  - cmake ..
  - make
