sudo: required
dist: trusty
#os: linux
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages: &default_packages
      - libopenmpi-dev
      - openmpi-bin
      - liblapack-dev
      - libatlas-base-dev
      - libatlas-dev
      - cmake
      - cmake-data
      - libvtk5-dev
      - libvtk5.8

cache:
  directories:
    - $HOME/cached_dependencies_$TRAVIS_OS_NAME

env:
   global:
    - CACHE_DIRECTORY=$HOME/cached_dependencies_$TRAVIS_OS_NAME
    - PETSC_ARCH=arch-linux2-c-opt

matrix:
  include:
    - env: GCC_VERSION=5 PETSC_VERSION=3.6.4
      os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - *default_packages
            - gcc-5
            - g++-5

    - env: GCC_VERSION=5 PETSC_VERSION=3.7.2
      os: linux
      addons: *gcc5

    - env: GCC_VERSION=6 PETSC_VERSION=3.6.4
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-6
            - g++-6

    - env: GCC_VERSION=6 PETSC_VERSION=3.7.2
      os: linux
      addons: *gcc6

    - env: CLANG_VERSION=3.7 PETSC_VERSION=3.6.4
      os: linux
      addons: &clang37
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - *default_packages
            - clang-3.7

    - env: CLANG_VERSION=3.7 PETSC_VERSION=3.7.2
      os: linux
      addons: *clang37

before_install:
  - travis_wait sh ./scripts/petsc.sh
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - export PETSC_DIR="${CACHE_DIRECTORY}/petsc-${PETSC_VERSION}"
  - which $CC
  - which $CXX

install:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4

script:
  - echo "OK"